language: python

# Enable python 3.7
dist: xenial

python:
  - 2.7
  - 3.4
  - 3.5
  - 3.6
  - 3.7
  - pypy
  - pypy3

install:
  - python setup.py install
  - pip install coverage coveralls

script:
  - make test

after_success:
  - bash <(curl -s https://codecov.io/bash)

matrix:
  allow_failures:
    - python: pypy3

sudo: false
